import { Section, P } from '../components/ui/Section'
import constants from '../data/constants.json'

const META = { id: 'boundaries', num: '14', title: 'Boundaries, honestly — and colophon' }

const LIMITS = [
  {
    t: 'Per-token attention KV required',
    d: 'Pure-recurrent (RWKV), pure-SSM (Mamba), and diffusion LMs are out of scope; hybrid attention+SSM models are only partially served — the recurrent state is not transplantable.',
  },
  {
    t: 'field+selective@K is unreliable by design',
    d: 'Conclusion stickiness is model- and domain-dependent (K★≈4 at 8B, >64 at 4B); the paper presents it as a measured tool, not a default.',
  },
  {
    t: 'Near-verbatim lookup is a partial exception',
    d: 'For attribute-lookup tasks the downstream note is partly a literal copy of the field, so field-only recovery is bounded (0.25–0.63) rather than ≈0.',
  },
  {
    t: 'Adapter edge cases remain',
    d: 'A single transplanted chunk that itself exceeds Gemma’s sliding window drops to logit cosine ≈0.89 (real skills are far smaller); small MLA checkpoints ship legacy-cache custom modeling that needs a shim.',
  },
  {
    t: 'The 2026 compressed frontier is analyzed, not implemented',
    d: 'Sequence-dimension KV compression (DeepSeek-V4-class CSA/HCA) makes the unit of edit/splice a block rather than a token; cross-attention image caches are likewise open.',
  },
  {
    t: 'Synthetic policies, mitigated',
    d: 'Several studies use synthetic policies for controlled measurement; the τ²-bench retail policy, real images, and LoCoMo conversations mitigate this. Broader real-workload evaluation remains future work.',
  },
  {
    t: 'Credit where due',
    d: 'The caching machinery (position-independent reuse, boundary recompute, RoPE repositioning) is prior art — Prompt Cache, CacheBlend, EPIC, CacheSlide, MPIC. The paper claims the mechanism, the unification, the decision-governance lens, and the attention-variant adapters.',
  },
]

export function Boundaries() {
  return (
    <Section meta={META}>
      <div className="prose">
        <div style={{ display: 'grid', gap: 10 }}>
          {LIMITS.map((l) => (
            <div key={l.t} style={{ background: '#fff', border: '1px solid var(--rule)', borderRadius: 6, padding: '12px 16px' }}>
              <div style={{ fontFamily: 'var(--sans)', fontSize: 13.5, fontWeight: 600, marginBottom: 3 }}>{l.t}</div>
              <div style={{ fontFamily: 'var(--sans)', fontSize: 12.5, color: 'var(--ink-soft)', lineHeight: 1.6 }}>{l.d}</div>
            </div>
          ))}
        </div>
      </div>

      <P>
        <strong>The closing lens.</strong> A surgical edit to a field&rsquo;s KV is ignored not
        because the cache is fragile but because the model already did the work: at prefill it
        memoizes the field-conditioned conclusion onto downstream aggregator tokens, and the
        decision reads those notes. The cache is a readable, writable record of what a model has
        already concluded — we hope the lens is useful well beyond editing and composition.
      </P>

      <div className="colophon">
        <p style={{ fontWeight: 600, marginBottom: 8 }}>Colophon</p>
        <p>
          This page is the interactive companion to <em>{constants.paper_meta.title}</em>{' '}
          ({constants.paper_meta.status.toLowerCase()}) Every number shown is read from the
          released result records and run logs that ship with the paper&rsquo;s code; prompts are
          regenerated by the released deterministic harness builders. The handful of values that
          exist only in the paper text are marked inline with a{' '}
          <span className="paper-const">⊙ from paper text</span> badge. Recorded model outputs are
          shown exactly as the harness stored them (tool call, thinking-token count, truncated
          answer head) — never reconstructed.
        </p>
        <div className="citation-block">{`@article{anonymous2026notes,
  title  = {Models Take Notes at Prefill:
            KV Cache Can Be Editable and Composable},
  author = {Anonymous Author(s)},
  note   = {Preprint. Under review.},
  year   = {2026}
}`}</div>
      </div>
    </Section>
  )
}
